### ISSUE TITLE
map_qsos.py fails when there are blank lines at the end of qso_update.csv

### ISSUE THREAD

**Issue by hcarter333** [hcarter333/rm-rbn-history#62]
The following error is created:

```
Working on N7WPO
Working on W4IDX
Working on WM6T
Working on

Traceback (most recent call last):
  File "C:\Users\m3n7es\source\rm-rbn-history\map_qso.py", line 38, in <module>
    map_qsos()
  File "C:\Users\m3n7es\source\rm-rbn-history\map_qso.py", line 10, in map_qsos
    result = dump_rm_rbn_history()
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m3n7es\source\rm-rbn-history\auto_geo_update.py", line 151, in dump_rm_rbn_history
    callsign_loc = get_call_lat_lng(fields[0])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\m3n7es\source\rm-rbn-history\auto_geo_update.py", line 103, in get_call_lat_lng
    lat=y["results"][0]["geometry"]["location"]["lat"]
        ~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by hcarter333** [comment]
This is now fixed. Code was added to ignore blank lines.

**Comment by hcarter333** [comment]
Fixed.
